default:
  image: node
  tags: [shared]
  before_script:
    - npm install

pages:
  script:
    - npx eleventy --pathprefix=grammatech.github.io/ --output=./public
  artifacts:
    paths:
      - public
